In [83]:
import pandas as pd 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [84]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\KPMG sem3\logistic Regression\creditworthiness-logistic-regression.csv')

In [85]:
display(df.head(10))

,Application id,income,age,employment,loan amount,previous default,debt,credit history,creditworthiness
0,APP00001,51944.0,59.0,Employed,35714,No,11202,Good,Yes
1,APP00002,26940.0,49.0,Self-Employed,85943,Yes,39104,Good,No
2,APP00003,39305.0,35.0,Employed,84884,No,41397,Good,Yes
3,APP00004,74354.0,63.0,Employed,14945,Yes,13538,Good,Yes
4,APP00005,129866.0,28.0,Employed,95234,No,14771,Good,Yes
5,APP00006,57424.0,41.0,Employed,22333,Yes,3318,Good,Yes
6,APP00007,69537.0,59.0,Employed,44364,Yes,3398,Poor,No
7,APP00008,92108.0,39.0,Unemployed,25440,No,29332,Poor,No
8,APP00009,41656.0,43.0,Self-Employed,86732,No,12586,Average,Yes
9,APP00010,70768.0,31.0,Employed,76193,No,73608,Good,Yes

In [86]:
print('total number of rows and columns in the dataset')
print(df.shape)

print('All columns in the dataset:')
print(df.columns)

print("statisticl summary")
df.describe()

#seelecting Target & Features

total number of rows and columns in the dataset
(10000, 9)
All columns in the dataset:
Index(['Application id', 'income', 'age', 'employment', 'loan amount',
       'previous default', 'debt', 'credit history', 'creditworthiness'],
      dtype='object')
statisticl summary

              income          age   loan amount          debt
count    9650.000000  9650.000000  10000.000000  10000.000000
mean    66482.348601    43.011813  52334.086700  40581.395300
std     31474.156483    12.894675  27432.039785  22726.725674
min     18000.000000    21.000000   5001.000000   1021.000000
25%     44289.750000    32.000000  28445.750000  21035.500000
50%     59937.500000    43.000000  52424.500000  40695.500000
75%     81526.500000    54.000000  75941.500000  60432.000000
max    250000.000000    65.000000  99980.000000  79976.000000

In [87]:
# info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Application id    10000 non-null  object
 1   income            9650 non-null   float64
 2   age               9650 non-null   float64
 3   employment        9650 non-null   object
 4   loan amount       10000 non-null  int64
 5   previous default  10000 non-null  object
 6   debt              10000 non-null  int64
 7   credit history    10000 non-null  object
 8   creditworthiness  10000 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [88]:
# missing values
print('Missing values in the dataset:')

df.isnull().sum()

Missing values in the dataset:

Application id        0
income              350
age                 350
employment          350
loan amount           0
previous default      0
debt                  0
credit history        0
creditworthiness      0
dtype: int64

# missing values handling

In [89]:
# replace missing values of age with median

df['age'] = df['age'].fillna(df['age'].median())

In [90]:
# replace missing values of income with median
df['income']= df['income'].fillna(df['income'].median())

In [91]:
# # replace missing values of employment with mode

df['employment']= df['employment'].fillna(df['employment'].mode()[0])

In [92]:
df.isnull().sum()

Application id      0
income              0
age                 0
employment          0
loan amount         0
previous default    0
debt                0
credit history      0
creditworthiness    0
dtype: int64

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:

df.describe()

              income           age   loan amount          debt
count   10000.000000  10000.000000  10000.000000  10000.000000
mean    66253.278900     43.011400  52334.086700  40581.395300
std     30941.786772     12.666985  27432.039785  22726.725674
min     18000.000000     21.000000   5001.000000   1021.000000
25%     44830.000000     32.000000  28445.750000  21035.500000
50%     59937.500000     43.000000  52424.500000  40695.500000
75%     80354.500000     54.000000  75941.500000  60432.000000
max    250000.000000     65.000000  99980.000000  79976.000000

# label Encoding

In [95]:
# label encoding 

categorical_cols = [
    'employment',
    'previous default',
    'credit history',
    'creditworthiness'
]

for col in categorical_cols:
    le=LabelEncoder()
    df[col]= le.fit_transform(df[col])

for col in categorical_cols:
    print(le.classes_)

['No' 'Yes']
['No' 'Yes']
['No' 'Yes']
['No' 'Yes']

In [96]:
df['employment']= le.fit_transform(df['employment'])
df['credit history']= le.fit_transform(df['credit history'])
df['creditworthiness']= le.fit_transform(df['creditworthiness'])
df['previous default']= le.fit_transform(df['previous default'])

In [97]:
df.head(10)

,Application id,income,age,employment,loan amount,previous default,debt,credit history,creditworthiness
0,APP00001,51944.0,59.0,0,35714,0,11202,1,1
1,APP00002,26940.0,49.0,1,85943,1,39104,1,0
2,APP00003,39305.0,35.0,0,84884,0,41397,1,1
3,APP00004,74354.0,63.0,0,14945,1,13538,1,1
4,APP00005,129866.0,28.0,0,95234,0,14771,1,1
5,APP00006,57424.0,41.0,0,22333,1,3318,1,1
6,APP00007,69537.0,59.0,0,44364,1,3398,2,0
7,APP00008,92108.0,39.0,2,25440,0,29332,2,0
8,APP00009,41656.0,43.0,1,86732,0,12586,0,1
9,APP00010,70768.0,31.0,0,76193,0,73608,1,1

In [98]:
# dropping application id 

df = df.drop("Application id", axis =1)

# selecting Target & Features

In [99]:

X = df.drop("creditworthiness", axis=1)
Y = df['creditworthiness']

In [100]:
print(X)
print('Y is \n', Y)

        income   age  employment  loan amount  previous default   debt  \
0      51944.0  59.0           0        35714                 0  11202
1      26940.0  49.0           1        85943                 1  39104
2      39305.0  35.0           0        84884                 0  41397
3      74354.0  63.0           0        14945                 1  13538
4     129866.0  28.0           0        95234                 0  14771
...        ...   ...         ...          ...               ...    ...
9995   80328.0  53.0           1        66463                 0   5300
9996   50411.0  36.0           1        70456                 0  73461
9997   89571.0  43.0           0        62802                 0  50419
9998  187073.0  63.0           0        98621                 0  13684
9999   51053.0  38.0           0        29795                 0  54835

      credit history
0                  1
1                  1
2                  1
3                  1
4                  1
...              ...
9995               1
9996               1
9997               1
9998               1
9999               1

[10000 rows x 7 columns]
Y is
 0       1
1       0
2       1
3       1
4       1
       ..
9995    1
9996    0
9997    1
9998    1
9999    1
Name: creditworthiness, Length: 10000, dtype: int64

In [101]:
# train test split 

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size = 0.20,
    random_state=42
)

In [102]:
# check the size 

print(f'Trainning data: {X_train.shape}')
print(f'Testing data: {X_test.shape}')

Trainning data: (8000, 7)
Testing data: (2000, 7)

In [103]:
model = LogisticRegression()

In [104]:
model.fit(X_train, Y_train)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [105]:
# make prediction 

y_pred = model.predict(X_test)

In [106]:
# view prediction 

print(y_pred[:20])

[1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 1 0]

### confusion matrix

In [107]:
# confusion matrix 
cm = confusion_matrix(Y_test, y_pred)

print(cm)

[[ 365  218]
 [ 140 1277]]

#### Accuracy Score

In [109]:
Acc= accuracy_score(Y_test, y_pred)
print(Acc)

0.821

### Recall

In [112]:
recall= recall_score(Y_test, y_pred)
print(recall)

0.9011997177134792

In [110]:
precission = precision_score(Y_test, y_pred)
print(precission)

0.854180602006689