In [28]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [5]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\KPMG sem3\fraud detection\raud-detection-lr.csv')

In [6]:
df.head(10)

,transaction_id,age,income,transaction_amount,account_age_days,transactions_24h,failed_attempts_24h,merchant_risk_score,distance_from_home_km,device_trust_score,is_international,is_new_device,transaction_hour,merchant_category,payment_method,is_fraud
0,1,23.0,30051.86,70.81,1400,5,2,0.1424,6.61,0.7174,0,0,1,gaming,card,0
1,2,62.0,40837.89,170.51,895,3,0,0.0680,7.05,0.8782,0,0,3,electronics,upi,0
2,3,55.0,63875.37,123.26,2136,6,0,0.2726,20.89,0.7289,0,0,11,electronics,net_banking,0
3,4,43.0,38929.69,408.65,58,4,0,0.0205,27.01,0.5039,0,0,1,grocery,upi,0
4,5,42.0,47192.34,420.26,2981,2,0,0.2680,2.13,0.7618,1,0,2,grocery,card,0
5,6,66.0,70111.05,28.72,2727,4,1,0.1128,3.82,0.8113,0,0,6,gaming,wallet,0
6,7,22.0,45399.82,511.87,3090,5,1,0.3509,4.51,0.9103,1,1,9,travel,wallet,1
7,8,57.0,62281.60,97.73,3270,7,0,0.3205,35.82,0.8394,0,0,17,food,upi,0
8,9,29.0,132070.23,227.98,3553,5,0,0.0957,10.13,0.8850,0,0,9,electronics,card,0
9,10,23.0,50039.41,70.39,617,2,0,0.0848,1.90,0.8792,0,0,9,travel,card,0

In [ ]:
print("columns and rows of dataset")

print(df.shape)
print("all columns list:  ")
for col in df.columns:
    print(col)

columns and rows of dataset
(10000, 16)
all columns list
transaction_id
age
income
transaction_amount
account_age_days
transactions_24h
failed_attempts_24h
merchant_risk_score
distance_from_home_km
device_trust_score
is_international
is_new_device
transaction_hour
merchant_category
payment_method
is_fraud

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   transaction_id         10000 non-null  int64
 1   age                    9649 non-null   float64
 2   income                 9547 non-null   float64
 3   transaction_amount     10000 non-null  float64
 4   account_age_days       10000 non-null  int64
 5   transactions_24h       10000 non-null  int64
 6   failed_attempts_24h    10000 non-null  int64
 7   merchant_risk_score    10000 non-null  float64
 8   distance_from_home_km  10000 non-null  float64
 9   device_trust_score     9802 non-null   float64
 10  is_international       10000 non-null  int64
 11  is_new_device          10000 non-null  int64
 12  transaction_hour       10000 non-null  int64
 13  merchant_category      9747 non-null   object
 14  payment_method         9801 non-null   object
 15  is_fraud               10000 non-null  int64
dtypes: float64(6), int64(8), object(2)
memory usage: 1.2+ MB

In [18]:
df.describe()

,transaction_id,age,income,transaction_amount,account_age_days,transactions_24h,failed_attempts_24h,merchant_risk_score,distance_from_home_km,device_trust_score,is_international,is_new_device,transaction_hour,is_fraud
count,10000.000000,9649.000000,9547.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.000000,9802.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5010.670600,45.832832,63861.855113,305.908919,2020.186800,4.033300,0.3408,0.199448,7.983083,0.800804,0.118100,0.148900,11.515300,0.125200
std,2886.602298,16.376761,37540.265032,374.543309,1139.043984,2.024747,0.5830,0.121574,7.951428,0.119020,0.322743,0.356008,6.943961,0.330962
min,1.000000,18.000000,15000.000000,5.000000,30.000000,0.000000,0.0000,0.001300,0.000000,0.217700,0.000000,0.000000,0.000000,0.000000
25%,2521.750000,32.000000,38072.190000,94.655000,1038.750000,3.000000,0.0000,0.106000,2.320000,0.727200,0.000000,0.000000,6.000000,0.000000
50%,5023.500000,46.000000,54237.070000,185.700000,2011.500000,4.000000,0.0000,0.176700,5.510000,0.820100,0.000000,0.000000,12.000000,0.000000
75%,7513.250000,60.000000,79356.720000,365.187500,2998.000000,5.000000,1.0000,0.273125,11.140000,0.892400,0.000000,0.000000,18.000000,0.000000
max,10000.000000,74.000000,250000.000000,5000.000000,3999.000000,13.000000,4.0000,0.737500,87.070000,0.997900,1.000000,1.000000,23.000000,1.000000

In [16]:
df.isnull().sum()

transaction_id             0
age                      351
income                   453
transaction_amount         0
account_age_days           0
transactions_24h           0
failed_attempts_24h        0
merchant_risk_score        0
distance_from_home_km      0
device_trust_score       198
is_international           0
is_new_device              0
transaction_hour           0
merchant_category        253
payment_method           199
is_fraud                   0
dtype: int64

In [21]:
df['age']= df['age'].fillna(df['age'].median())
df['income']= df['income'].fillna(df['income'].median())
df['device_trust_score']=df['device_trust_score'].fillna(df['device_trust_score'].median())
df['merchant_category'] = df['merchant_category'].fillna(df['merchant_category'].mode()[0])
df['payment_method'] = df['payment_method'].fillna(df['payment_method'].mode()[0])

In [22]:
df.duplicated().sum()

np.int64(197)

In [23]:
df= df.drop_duplicates()

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

transaction_id           0
age                      0
income                   0
transaction_amount       0
account_age_days         0
transactions_24h         0
failed_attempts_24h      0
merchant_risk_score      0
distance_from_home_km    0
device_trust_score       0
is_international         0
is_new_device            0
transaction_hour         0
merchant_category        0
payment_method           0
is_fraud                 0
dtype: int64

In [29]:
le =LabelEncoder()
df['merchant_category']= le.fit_transform(df['merchant_category'])
df['payment_method']= le.fit_transform(df['payment_method'])

C:\Users\HP\AppData\Local\Temp\ipykernel_19020\3179862664.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['merchant_category']= le.fit_transform(df['merchant_category'])
C:\Users\HP\AppData\Local\Temp\ipykernel_19020\3179862664.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_method']= le.fit_transform(df['payment_method'])

In [30]:
df.head()

,transaction_id,age,income,transaction_amount,account_age_days,transactions_24h,failed_attempts_24h,merchant_risk_score,distance_from_home_km,device_trust_score,is_international,is_new_device,transaction_hour,merchant_category,payment_method,is_fraud
0,1,23.0,30051.86,70.81,1400,5,2,0.1424,6.61,0.7174,0,0,1,3,0,0
1,2,62.0,40837.89,170.51,895,3,0,0.0680,7.05,0.8782,0,0,3,0,2,0
2,3,55.0,63875.37,123.26,2136,6,0,0.2726,20.89,0.7289,0,0,11,0,1,0
3,4,43.0,38929.69,408.65,58,4,0,0.0205,27.01,0.5039,0,0,1,4,2,0
4,5,42.0,47192.34,420.26,2981,2,0,0.2680,2.13,0.7618,1,0,2,4,0,0

In [35]:
X = df.drop('is_fraud', axis =1)
Y = df['is_fraud']
print(X.shape)
print(X.columns)
print(Y.shape)

(9803, 15)
Index(['transaction_id', 'age', 'income', 'transaction_amount',
       'account_age_days', 'transactions_24h', 'failed_attempts_24h',
       'merchant_risk_score', 'distance_from_home_km', 'device_trust_score',
       'is_international', 'is_new_device', 'transaction_hour',
       'merchant_category', 'payment_method'],
      dtype='object')
(9803,)

In [36]:
X_train, X_test, Y_train, Y_test =train_test_split(
    X,
    Y,
    test_size=0.3,
    random_state=42
)

In [37]:
# check
#  the size 

print(f'Trainning data: {X_train.shape}')
print(f'Testing data: {X_test.shape}')

Trainning data: (6862, 15)
Testing data: (2941, 15)

In [38]:
model= LogisticRegression()

In [39]:
model.fit(X_train, Y_train)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [40]:
y_pred = model.predict(X_test)

In [42]:
print(y_pred[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [43]:
# confusion matrix 
cm = confusion_matrix(Y_test, y_pred)

print(cm)

[[2571    0]
 [ 369    1]]

In [51]:
# Accuracy 
accuracy = accuracy_score(Y_test, y_pred)
print(accuracy)

0.8745324719483168

In [46]:
# precision 
precision = precision_score(Y_test, y_pred) 
print(precision)

1.0

In [47]:
Acc= accuracy_score(Y_test, y_pred)
print(Acc)

0.8745324719483168

In [48]:
recall= recall_score(Y_test, y_pred)
print(recall)

0.002702702702702703

In [50]:
precission = f1_score(Y_test, y_pred)
print(precission)

0.005390835579514825