In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\KPMG sem3\Polynomial Regession\house-price-polynomial.csv')

In [4]:
df.head()

,Area_sqft,Bedrooms,Bathrooms,Age_years,Distance_to_city_km,Parking_spaces,Price_INR
0,3674,6,5,20,9.6,3,4774673
1,1360,2,1,34,4.1,1,1533033
2,1794,3,2,31,23.7,2,1385438
3,1630,2,1,29,19.7,2,946869
4,1595,2,1,38,2.4,0,1765615

In [5]:
df.isnull().sum()

Area_sqft              0
Bedrooms               0
Bathrooms              0
Age_years              0
Distance_to_city_km    0
Parking_spaces         0
Price_INR              0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
x= df[['Area_sqft', 'Bedrooms','Bathrooms', 'Age_years', 'Distance_to_city_km', 'Parking_spaces']]

y= df['Price_INR']
print(x.shape)
print(y.shape)

(1000, 6)
(1000,)

In [8]:
from sklearn.model_selection import train_test_split
# 80 % trainning data and 20% testing data 
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [9]:
from sklearn.preprocessing import PolynomialFeatures

# create po;lynomial featues of degree 2

poly = PolynomialFeatures(degree=2)

x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.fit_transform(x_test)

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train_poly, y_train)

print("Model trainning completed")

Model trainning completed

In [11]:
y_pred = model.predict(x_test_poly)

# compare actual and predicted price 

result = pd.DataFrame({
    'Actual Price': y_test.values,
    'Predicted Price': y_pred.round(0)
})
result.head(10)

   Actual Price  Predicted Price
0       5058746        4820652.0
1       5312318        5481223.0
2       4153608        4153897.0
3       4391204        4269043.0
4       2364308        2073907.0
5       4662855        4707882.0
6       2547276        2239283.0
7       1676546        1745148.0
8       1238306        1339181.0
9       3382957        3371666.0

In [12]:
from sklearn.metrics import r2_score

r2 = r2_score(result['Actual Price'], y_pred)

print(f'R2 is {r2}')

# Display with 3 decimal places
print(f"R2 Score: {r2:.3f}")


# Display as a percentage with 1 decimal place
print(f"Model Accuracy: {r2 * 100:.1f}%")

R2 is 0.9819605367343781
R2 Score: 0.982
Model Accuracy: 98.2%

In [13]:
new_house =pd.DataFrame({
    'Area_sqft':[3000],
    'Bedrooms':[4],
    'Bathrooms':[1],
    'Age_years':[25],
    'Distance_to_city_km':[20],
    'Parking_spaces':[1]
})

# convert the new house data into polynomial features
new_house_poly = poly.transform(new_house)

# predict the price
predicted_price = model.predict(new_house_poly)

print(f'Predicted price is : Rs. {predicted_price}')

Predicted price is : Rs. [3079866.91581361]

In [14]:
import pickle

# Save your trained model to a file named 'poly_model.pkl'
with open('poly_model.pkl', 'wb') as file:
    pickle.dump(model, file)  # Replace 'model' with your actual variable name

print("Model successfully saved as poly_model.pkl!")

Model successfully saved as poly_model.pkl!

# statistics

In [21]:
# select numerical columns 
import numpy as np
num_col = df.select_dtypes(include=np.number).columns

# check skewness of each numerical column
print("skewness")
print(df[num_col].skew().round(2))

# fill missing values based on skewness

for col in num_col:

    # calculate skewness using available values 
    skew_values = df[col].skew()

    # if skewness is between -0.5 and +0.5 use mean
    if 0.5 <= skew_values <=0.5:
        df[col]=df[col].fillna(df[col].mean())
        print(col, "-> Filled with Mean")

        # otherwize use mediuan

    else:
        df[col] =df[col].fillna(df[col].median())
        print(col, "-> Filled with Median")

skewness
Area_sqft              0.01
Bedrooms              -0.01
Bathrooms              0.05
Age_years             -0.03
Distance_to_city_km    0.00
Parking_spaces        -0.19
Price_INR              0.29
dtype: float64
Area_sqft -> Filled with Median
Bedrooms -> Filled with Median
Bathrooms -> Filled with Median
Age_years -> Filled with Median
Distance_to_city_km -> Filled with Median
Parking_spaces -> Filled with Median
Price_INR -> Filled with Median