In [43]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [44]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\KPMG sem3\Linear_Regresiion\credit-scoring-ML.csv')

In [45]:
df.head(10)

,Age,Gender,Annual_Income,Employment_Years,Existing_Debt,Credit_History_Years,Num_Credit_Accounts,Late_Payments,Loan_Amount,Credit_Score
0,34.0,Male,40097,18.4,3535,14.8,3,1,20958,612
1,38.0,Male,106517,11.2,51623,17.0,5,2,33969,639
2,25.0,Male,126111,7.0,72888,6.1,6,4,57275,495
3,38.0,Male,58212,5.1,35693,14.3,5,5,27459,506
4,39.0,Male,56142,0.9,32303,20.2,3,2,50193,540
5,42.0,Male,56041,7.8,8163,11.4,6,2,65073,583
6,40.0,Male,96005,2.2,59643,10.4,5,2,67034,526
7,36.0,Female,104362,8.4,49652,8.3,6,3,23232,552
8,34.0,Female,94909,4.2,18312,12.4,10,1,49616,560
9,63.0,Male,32967,8.1,10077,38.3,7,2,9871,658

In [46]:
df.tail(10)

,Age,Gender,Annual_Income,Employment_Years,Existing_Debt,Credit_History_Years,Num_Credit_Accounts,Late_Payments,Loan_Amount,Credit_Score
9990,58.0,Male,47426,3.4,3803,30.2,8,1,35941,635
9991,27.0,Female,92390,9.0,38516,5.5,6,0,35261,585
9992,44.0,Male,78616,6.6,30132,20.5,4,1,83893,601
9993,37.0,Male,49176,8.8,25695,14.4,8,0,16371,607
9994,54.0,Male,91010,12.6,37928,32.3,5,0,92689,643
9995,34.0,Male,104033,3.3,65929,14.8,6,1,122204,540
9996,23.0,Female,31232,11.1,8410,1.0,6,0,7163,562
9997,33.0,Female,90841,3.8,27333,1.9,6,2,41834,488
9998,25.0,Male,49330,1.5,10399,2.0,7,2,55098,520
9999,38.0,Male,46515,11.7,29636,19.5,4,3,13020,574

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9898 non-null   float64
 1   Gender                9899 non-null   object
 2   Annual_Income         10000 non-null  int64
 3   Employment_Years      10000 non-null  float64
 4   Existing_Debt         10000 non-null  int64
 5   Credit_History_Years  10000 non-null  float64
 6   Num_Credit_Accounts   10000 non-null  int64
 7   Late_Payments         10000 non-null  int64
 8   Loan_Amount           10000 non-null  int64
 9   Credit_Score          10000 non-null  int64
dtypes: float64(3), int64(6), object(1)
memory usage: 781.4+ KB

In [48]:
df.isnull().sum()

Age                     102
Gender                  101
Annual_Income             0
Employment_Years          0
Existing_Debt             0
Credit_History_Years      0
Num_Credit_Accounts       0
Late_Payments             0
Loan_Amount               0
Credit_Score              0
dtype: int64

# missing value Handling

In [49]:
mean_age = df['Age'].mean()

df['Age'] = df['Age'].fillna(mean_age)

In [50]:
df['Gender']= df['Gender'].fillna(df['Gender'].mode()[0])

In [51]:
df['Age'].isnull().sum()
df['Gender'].isnull().sum()

np.int64(0)

In [52]:
# count duplicate rows 

df.duplicated().sum()

np.int64(200)

In [53]:
# drop duplicate rows 

df= df.drop_duplicates()

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
# X = independent variable
# Y = Target variables 

X = df.drop("Credit_Score",axis=1)
Y = df['Credit_Score']

print("Independent Variables:")
print(X.columns)

print("\nTarget Variable")
print(Y.name)

Independent Variables:
Index(['Age', 'Gender', 'Annual_Income', 'Employment_Years', 'Existing_Debt',
       'Credit_History_Years', 'Num_Credit_Accounts', 'Late_Payments',
       'Loan_Amount'],
      dtype='object')

Target Variable
Credit_Score

In [56]:
X= pd.get_dummies(X, columns=['Gender'], drop_first=True)
X.head()

,Age,Annual_Income,Employment_Years,Existing_Debt,Credit_History_Years,Num_Credit_Accounts,Late_Payments,Loan_Amount,Gender_Male
0,34.0,40097,18.4,3535,14.8,3,1,20958,True
1,38.0,106517,11.2,51623,17.0,5,2,33969,True
2,25.0,126111,7.0,72888,6.1,6,4,57275,True
3,38.0,58212,5.1,35693,14.3,5,5,27459,True
4,39.0,56142,0.9,32303,20.2,3,2,50193,True

In [57]:
 

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size = 0.20,
    random_state=42
)

print("Trainning data: ", X_train.shape)
print("Testing data: ", X_test.shape)

Trainning data:  (7840, 9)
Testing data:  (1960, 9)

In [58]:
model = LinearRegression()

In [59]:
model.fit(X_train, Y_train)

LinearRegression()

In [62]:
from sklearn.metrics import r2_score
# make prediction on the test set

y_pred = model.predict(X_test)

# calculate R2 score
r2 = r2_score(Y_test, y_pred)

print("R2 Score:",r2)

# for Regression, R2 score is one of the most commonly used evaluation matrics

R2 Score: 0.8021886374036977

In [85]:
# enter information about a new customer

age = float(input("Enter Age:"))
gender= input("Enter Gender (Male/Female)")
income= float(input("Enter Annual Income"))
employment_year = float(input("Enter enployment years "))
existing_debt = float(input("Ener existing loan amount"))
credit_history_year = float(input("Enter credit history of"))
num_credit_accounts =float(input("Enter number of Credit Account"))
late_payments = float(input("Enter Number of Late Payment"))
loan_amount = float(input("Enter Loan Amount"))

In [86]:
new_customer = pd.DataFrame({
    "Age": [age],
    "Annual_Income": [income],
    "Employment_Years": [employment_year],
    "Existing_Debt": [existing_debt],
    "Credit_History_Years": [credit_history_year],
    "Num_Credit_Accounts": [num_credit_accounts],
    "Late_Payments": [late_payments],
    "Loan_Amount": [loan_amount],
    "Gender_Male": [1 if gender.strip().lower() == "male" else 0]
})

# Display the new customer
new_customer

,Age,Annual_Income,Employment_Years,Existing_Debt,Credit_History_Years,Num_Credit_Accounts,Late_Payments,Loan_Amount,Gender_Male
0,28.0,500000.0,2.0,10000.0,1.0,2.0,1.0,50000.0,1

In [89]:
# Predict the Credit Score

predicted_score = model.predict(new_customer)[0]

print("Predicted Credit Score:", round(predicted_score, 2))

Predicted Credit Score: 735.95